version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/wtaiatella
  - source: /home/ec2-user/env/
    destination: /var/www/wtaiatella
hooks:
  DownloadBundle:
    - location: ./scripts/deployDownloadBundle.sh
      timeout: 30
      runas: ec2-user
  BeforeInstall:
    - location: ./scripts/deployBeforeInstall.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: ./scripts/deployAfterInstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./scripts/deployApplicationStart.sh
      timeout: 30
      runas: ec2-user
