import type { NextPage } from 'next';
import Head from 'next/head';
import { FrontScreen } from '../components/FrontScreen';
import { Header } from '../components/Header';
import { About } from '../components/About';
import { MyLearning } from '../components/MyLearning';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<FrontScreen />
			<Header />
			<About />
			<MyLearning />
		</>
	);
};

export default Home;
